---
title: "Figure 1. Example data"
author: "Jason T. Serviss"
date: "12/12/2016"
output:
  html_document:
    theme: flatly
    toc: yes
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{ClusterSignificance Vignette} 
  %\VignetteEngine{knitr::rmarkdown} 
  %\usepackage[utf8]{inputenc}
  %\SweaveUTF8
---

# Read Me
This data is used to as an easy example to understand the purpose of ClusterSignificance. It is set up so that the results can easily be anticipated before ClusterSignificance is run.

```{r, message =FALSE}
library(ClusterSignificanceTesting)

#create data
set.seed=123
mat1 <- hundred['30.points'][[1]][,,1]
add <- sample(seq(min(mat1), max(mat1), 0.001), replace=FALSE, size=30)
mat1 <- cbind(mat1, add)
mat2 <- matrix(sapply(1:3, function(x)
    c(sample(seq(50, 150, 0.001),
    replace=FALSE,
    size=30))
), ncol=3)

mat <- rbind(mat1, mat2)
groups <- c(rep("grp1", 30), rep("grp2", 30), rep("grp3", 30))

#run ClusterSignificance projection and change colors
prj <- pcp(mat, groups)
group.color <- getData(prj, "group.color")
group.color[1,] <- c(68, 221, 136)
group.color[2,] <- c(170, 204, 34)
group.color[3,] <- c(153, 119, 85)
prj@group.color <- group.color

#run CLusterSignificance classification
cl <- classify(prj)

#run ClusterSignificance permutation
set.seed(3)
pe <- permute(mat, groups, "pcp", 10000)
```

# Re-create Figure 1.
## Projection

```{r, fig.align='center', fig.height=8, fig.width=10, eval=TRUE, message=FALSE}
plot(prj, steps=3, alpha=0.75, cex.lab = 2, cex.axis = 2, cex.symbols = 3, cex.legend=2, pt.cex.legend=3)
```

## Classification

```{r, fig.align='center', fig.height=8, fig.width=10, eval=TRUE, message=FALSE}
plot(cl, cex.points=3, cex.main=2, cex.lab=2, cex.axis=2)
```

## Permutation

```{r, fig.align='center', fig.height=8, fig.width=10, eval=TRUE, message=FALSE}
plot(pe, cex.main=2, cex.lab=1.5, cex.axis=2, abline.lwd=1.5)
```
